Nav bar imporvement
CS450-ECE461/fall2016-group2-userportal pull request #70
Opened 2016-12-10 20:11 UTC by Lrthayer

added bootstrap for nav bar, changed the external css file to dashboard.css and played with the icon sizes.

2016-12-10 20:32 UTC, DannyPeck requested changes
I noticed when testing it that the buttons have different hit boxes, can we see if we can change that so that the buttons have the same hit boxes but we shrink the image?  Can probably use padding for this.

2016-12-10 20:32 UTC, DannyPeck commented on app/views/login.pug
> +        img(style='display: block; margin: auto; height:250px; margin-top:50px; ' src='/assets/hive.png')
Perfect, glad we changed the file names.

2016-12-10 20:32 UTC, DannyPeck commented on app/views/dashboard.pug
> +                input(class="contacts" style='width:100%; height:100%;' type='image' width='230' height='230' src="/assets/Contacts.png" alt='Submit' href='#')
What was the purpose of setting the width and height properties?

2016-12-10 20:32 UTC, DannyPeck commented on app/views/dashboard.pug
> +                input(id='home' style='width:100%; height:100%;' type='image' src="/assets/hive.png" alt='Submit' href='#')
What does href='#' do?

2016-12-10 20:32 UTC, DannyPeck commented on app/views/dashboard.pug
> +        nav(class="navbar navbar-nav" id='navBar' style='position:absolute;width:10%;height:100%;left:0%;top:0%;border-style:solid;background-color:rgb(49,60,80);')
Are these both bootstrap classes?

2016-12-10 20:34 UTC, Lrthayer commented on app/views/dashboard.pug
> +        nav(class="navbar navbar-nav" id='navBar' style='position:absolute;width:10%;height:100%;left:0%;top:0%;border-style:solid;background-color:rgb(49,60,80);')
when you say both, you mean navbar and navbar-nav?

2016-12-10 20:35 UTC, Lrthayer commented on app/views/dashboard.pug
> +                input(id='home' style='width:100%; height:100%;' type='image' src="/assets/hive.png" alt='Submit' href='#')
it's suppose to pass the active class, it didn't really make sense to me but that is what I found via bootstrap tutorial, it didn't work anyway so I'll just get rid of those.

2016-12-10 20:35 UTC, Lrthayer commented on app/views/dashboard.pug
> +                input(class="contacts" style='width:100%; height:100%;' type='image' width='230' height='230' src="/assets/Contacts.png" alt='Submit' href='#')
ah, forgot to change that back... it was for testing. I will get rid of that.

2016-12-10 20:39 UTC, Lrthayer commented on app/views/dashboard.pug
> +        nav(class="navbar navbar-nav" id='navBar' style='position:absolute;width:10%;height:100%;left:0%;top:0%;border-style:solid;background-color:rgb(49,60,80);')
if so, yes. I'm pretty sure it let's bootstrap know it's not a default navbar, that way it doesn't try to force a horizontal bar.

2016-12-11 01:04 UTC, timwhitf approved these changes

2016-12-11 01:10 UTC, merged